# Generated by Django 3.1.7 on 2021-03-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasketballPlayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                ("age", models.PositiveIntegerField()),
                ("points_scored", models.PositiveIntegerField()),
                ("assists", models.PositiveIntegerField()),
                ("rebounds", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SoccerPlayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                ("age", models.PositiveIntegerField()),
                ("goals_scored", models.PositiveIntegerField()),
                ("assists", models.PositiveIntegerField()),
                ("yellow_cards", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
